version: '3.8'

services:
  db:
    container_name: SpringCourse
    image: postgres
    environment:
      POSTGRES_USER: Tammam
      POSTGRES_PASSWORD: Mohammed
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5544:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: